sudo: false
dist: trusty
language: node_js
node_js: node

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - npm install -g bower
  - bower install

before_script:
  - gulp lint

script:
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
