sudo: false
dist: trusty
language: node_js
node_js: node

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

before_script:
  - gulp lint

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      wdio wdio.conf.js;
    fi
